name: tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version: ["3.10", "3.12", "3.14"]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v7
      - uses: mamba-org/setup-micromamba@v3
        with:
          environment-file: environment.yml
          create-args: python=${{ matrix.python-version }}
      - run: pip install --no-deps -e .
      - run: pytest -v
